# Generated by Django 4.1.5 on 2023-02-16 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pintrestapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='phonenumber',
            field=models.BigIntegerField(default=0),
        ),
    ]
