# Generated by Django 4.1.5 on 2023-02-17 08:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pintrestapp', '0002_alter_userdetails_phonenumber'),
    ]

    operations = [
        migrations.CreateModel(
            name='comments',
            fields=[
                ('serialno', models.AutoField(primary_key=True, serialize=False)),
                ('comment', models.TextField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('parcommt', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pintrestapp.comments')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pintrestapp.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
