# Generated by Django 4.1.5 on 2023-02-18 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pintrestapp', '0003_comments'),
    ]

    operations = [
        migrations.DeleteModel(
            name='comments',
        ),
    ]
